name: publish-forgebox-package
description: This is an action to publish your package to forgebox
author: Pixl8 Group
branding:
  icon: 'upload'
  color: 'green'
runs:
  using: 'docker'
  # image: 'docker://pixl8/github-action-box-publish:v1'
  image: 'Dockerfile'
